# Generated by Django 4.0 on 2022-01-22 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_rename_title_product_name_order_transaction_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='detail',
            field=models.TextField(null=True, unique=True),
        ),
    ]
